# linear and angular speed limits for the robot
max_v: 1.2 # m/s
max_w: 0.15 # rad/s
# observation rate fo the robot
frame_rate: 6 # Hz
graph_rate: 0.3333 # Hz

# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop
vel_navi_topic: /cmd_vel_mux/input/navi
vel_recovery_topic: /cmd_vel_mux/input/recovery
